name: Advent 2021
  on:
    push:
      paths:
      - '2021/**'
jobs:
  AOC-2021:
    runs-on: ubuntu-latest

    container: 
      image: python:bullseye

    steps:
    - uses: actions/checkout@v2
    - name: AoC 2021 - Dep
      shell: bash
      run: python3.10 -m pip install numpy regex

    - name: AoC 2021 - Run
      shell: bash
      run: |
        for d in ${GITHUB_WORKSPACE}/2021/*/ ; do
          echo "Running day $(basename ${d})"
          for p in ${d}code* ; do
              python3.10 ${p} ${d}/data
          done
          echo
        done
