name: AoC - 2022

on:
  push:
    paths:
      - .github/workflows/2022.yml
      - '2022/**'

jobs:
  AOC-2022:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: AoC 2022 - Build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/2022/
        cargo build --release

    - name: AoC 2022 - Run
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/2022/
        for d in ${GITHUB_WORKSPACE}/2022/*/ ; do
          echo "Running day $(basename ${d})"
          cargo run --bin $(basename ${d}) $(basename ${d})/data
          echo
        done
