name: AoC - 2023

on:
  push:
    paths:
      - .github/workflows/2023.yml
      - '2023/**'

jobs:
  AOC-2023:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Aoc 2023 - Deps
      shell: bash
      run: |
        apt-get install ninja -qq

    - name: AoC 2023 - Build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/2023/
        bash build.sh

    - name: AoC 2023 - Run
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/2023/
        for d in ${GITHUB_WORKSPACE}/2023/d*/ ; do
          echo "Running day $(basename ${d})"
          $(basename ${d}) $(basename ${d})/data
          echo
        done
