name: Advent Of Ci
on: push
jobs:
  Submarine-2021:
    runs-on: ubuntu-latest
    container: 
      image: python:bullseye
    steps:
    - name: Run Submarine
      run: |
        for d in ${GITHUB_WORKSPACE}/*/ ; do
          for p in ${d}code* ; do
              python3.10 ${p} ${d}/data
          done
        done
